name: Compile Android APK

on:
  workflow_dispatch: # Permet le déclenchement propre en un clic

# Force GitHub à utiliser le sous-dossier mobile comme point de départ
defaults:
  run:
    working-directory: mobile

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Recuperer le code source
        uses: actions/checkout@v4

      - name: Installer Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Installer Flutter Specifique
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
          cache: true

      - name: Récupérer les paquets de l'application
        run: flutter pub get

      - name: Generer les fichiers de configuration manquants
        run: flutter create . --platforms=android

      - name: Compiler en APK officiel
        run: flutter build apk --release --no-tree-shake-icons

      - name: Sauvegarder l'APK fini
        uses: actions/upload-artifact@v4
        with:
          name: Mon-Application-Android
          path: mobile/build/app/outputs/flutter-apk/app-release.apk
