name: Compile Android APK

on:
  workflow_dispatch: # Permet de forcer manuellement le démarrage propre avec le bouton

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Recuperer le code source
        uses: actions/checkout@v4

      - name: Installer Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Installer Flutter Specifique
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0' # Version stable et compatible pour ce projet
          channel: 'stable'

      - name: Forcer le nettoyage des paquets
        run: |
          cd mobile
          flutter pub cache clean --force
          flutter pub get

      - name: Compiler en APK
        run: |
          cd mobile
          flutter build apk --release --no-tree-shake-icons

      - name: Sauvegarder l'APK
        uses: actions/upload-artifact@v4
        with:
          name: Mon-Application-Android
          path: mobile/build/app/outputs/flutter-apk/app-release.apk
